### ISSUE TITLE
my problems of Unsupervised feature selection based on adaptive similarity learning and subspace clustering

### ISSUE THREAD

**Issue by fzujcr** [mohsengh/SCFS#1]
Dear Dr Zare,
 

 I am JianCairen from Xiamen University, China. I am very thank you for your opening python code of scfs(Unsupervised feature selection based on adaptive similarity learning and subspace clustering).I am sorry, beause that I can not get the convergence result using your python code and my matlab code of scfs.
 

  So can I get the matlab code of the scfs from you.

  Thank you for your attention.I am looking forward to you.

Best Regards,
Jian Cairen
Email：fzujcr@qq.com

**Comment by mohsengh** [comment]
Dear JianCairen
Thank you to read our paper and using our code.
We don't have any version of our code in matlab. I attached our code in python with some print to show the convergency of our code and the log file is also attached. The version of python that I used to run the code is 2.7.

Please cite our paper (Unsupervised feature selection based on adaptive similarity learning and subspace clustering), if it is useful for your research.

Regards,
Mohsen Ghassemi Parsa
[Uploading SCFS.zip…]()
